### PR TITLE
Account collection

### PR DESCRIPTION
**Pull request by magicpaIm**
For #50

### CODE REVIEW

**Comment by Behzad-rabiei** [comment]
test('should correctly validate a valid channel data', async () => {
      await expect(new Account(account).validate()).resolves.toBeUndefined();
    });

it should be 'should correctly validate a valid account data'

**Comment by Behzad-rabiei** [comment]
export interface IAccount {
  id: Snowflake;
  account: string;
  roles: Array<string>;
  joinDate: Date;
  joinedChannel: Snowflake;
}


is the Id related to Discord? if yes please specify what is the id. for example in User schema we have the discordId or in guild we have the guildId

**Comment by Behzad-rabiei** [comment]
do we need accountSchema.plugin(mongooseUniqueValidator); for account model?

**Comment by Behzad-rabiei** [comment]
const data = await model.findOne({
    id: id,
  });

you can do it like this : 
  const data = await model.findOne({
    id
  });

btw it does not cause error it s just a style.

**Comment by magicpaIm** [comment]
> ```
> test('should correctly validate a valid channel data', async () => {
>   await expect(new Account(account).validate()).resolves.toBeUndefined();
> });
> ```
> 
> it should be 'should correctly validate a valid account data'



> export interface IAccount { id: Snowflake; account: string; roles: Array; joinDate: Date; joinedChannel: Snowflake; }
> 
> is the Id related to Discord? if yes please specify what is the id. for example in User schema we have the discordId or in guild we have the guildId

That is account id. If it is anonymous, I will change it.

**Comment by magicpaIm** [comment]
> do we need accountSchema.plugin(mongooseUniqueValidator); for account model?

Yes, because every account should be unique with their account id.

**Pull request merged**
